# Generated by Django 5.2.6 on 2025-09-11 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="The crypto wallet address.", max_length=255
                    ),
                ),
                (
                    "currency_type",
                    models.CharField(
                        choices=[
                            ("eth", "Ethereum"),
                            ("btc", "Bitcoin"),
                            ("sol", "Solana"),
                            ("other", "Other"),
                        ],
                        help_text="The type of cryptocurrency.",
                        max_length=10,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Is this address visible on the public profile?",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has ownership of this address been verified?",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Addresses",
                "unique_together": {("user", "address")},
            },
        ),
        migrations.CreateModel(
            name="SnsLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter"),
                            ("github", "GitHub"),
                            ("website", "Website"),
                            ("other", "Other"),
                        ],
                        help_text="The social media platform.",
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The URL of the user's profile on the platform."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sns_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "platform")},
            },
        ),
    ]
